//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

//this header file is extremely stripped down. Only has the one thing we need, igtvButton.

@class IGBadgeButton, IGBadgingTooltipNubView, IGGradientLineRefreshControl, IGTapButton, NSString, UIButton;

@interface IGMainAppHeaderView : UIView 
{
    IGBadgeButton *_igtvButton;
}

@property(readonly, nonatomic) UIButton *igtvButton; // @synthesize igtvButton=_igtvButton;

@end
